int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int helper(int n, int i);
int is_prime_number(int n);
int prime_number(int n, int i);
int is_palindrome(char *s);
int _strlen(char *s);
int helper_palindrome(char *s, int i, int length);
int wildcmp(char *s1, char *s2);
int wildcmp_helper(char *s1, char *s2, int i, int len1, int len2);
int wildcard_handler(char *s1, char *s2, int i1, int i2);
